version: '3.8' # Docker Compose 파일 버전 명시

services:
  # Spring Boot 개발 환경 컨테이너 서비스
  springboot-dev:
    # 컨테이너 이름 설정
    container_name: springboot-dev-container
    # 빌드 컨텍스트 및 Dockerfile 경로 지정
    build:
      context: ./springboot
      dockerfile: Dockerfile
    # 포트 매핑 (호스트:컨테이너)
    ports:
      - "8080:8080" # Spring Boot 애플리케이션 포트
    # 작업 디렉토리 마운트 (소스 코드 변경 실시간 반영)
    # 호스트의 ./springboot/workspace 를 컨테이너의 /home/dev/workspace 로 연결
    # 실제 프로젝트 경로에 맞게 수정해주세요.
    volumes:
      - ./springboot/workspace:/home/dev/workspace
    # 데이터베이스 서비스들이 시작된 후에 이 서비스가 시작되도록 의존성 설정
    depends_on:
      - mysql-db
      - postgres-db
      - oracle-db
    # 애플리케이션이 데이터베이스에 연결하기 위한 환경 변수 설정
    environment:
      # MySQL 연결 정보
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/${MYSQL_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
      # PostgreSQL 연결 정보 (Spring Boot는 프로필 등을 통해 둘 중 하나를 선택하여 사용)
      SPRING_DATASOURCE_PG_URL: jdbc:postgresql://postgres-db:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_PG_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PG_PASSWORD: ${POSTGRES_PASSWORD}
      # Oracle 연결 정보 (Spring Boot는 프로필 등을 통해 DB 선택)
      # Oracle XE의 기본 SID는 'XE' 입니다.
      SPRING_DATASOURCE_ORACLE_URL: jdbc:oracle:thin:@oracle-db:1521:XE
      SPRING_DATASOURCE_ORACLE_USERNAME: ${ORACLE_USER}
      SPRING_DATASOURCE_ORACLE_PASSWORD: ${ORACLE_PASSWORD}
    # 컨테이너가 종료되지 않도록 유지 (개발 중 디버깅 등에 유용)
    # 실제 애플리케이션 실행 명령어로 변경 필요 시 수정
    tty: true
    stdin_open: true

  # MySQL 데이터베이스 서비스
  mysql-db:
    container_name: mysql-db-container
    build:
      context: ./mysql
      dockerfile: Dockerfile
    ports:
      - "3306:3306" # MySQL 포트
    environment:
      # .env 파일 또는 환경 변수에서 값을 가져옵니다.
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      # MySQL 데이터 영구 저장을 위한 볼륨 설정
      - mysql_data:/var/lib/mysql

  # PostgreSQL 데이터베이스 서비스
  postgres-db:
    container_name: postgres-db-container
    build:
      context: ./postgresql
      dockerfile: Dockerfile
      args:
        POSTGRES_DB_ARG: ${POSTGRES_DB}
        POSTGRES_USER_ARG: ${POSTGRES_USER}
        POSTGRES_PASSWORD_ARG: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432" # PostgreSQL 포트
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      # PostgreSQL 데이터 영구 저장을 위한 볼륨 설정
      - postgres_data:/var/lib/postgresql/data

  # Oracle 데이터베이스 서비스
  oracle-db:
    container_name: oracle-db-container
    build:
      context: ./oracle
      dockerfile: Dockerfile
    ports:
      - "1521:1521" # Oracle 포트
    environment:
      # .env 파일에서 값을 가져옵니다.
      # SYS, SYSTEM 사용자의 비밀번호. gvenzl/oracle-xe 이미지는 이 변수를 사용합니다.
      ORACLE_PASSWORD: ${ORACLE_ROOT_PASSWORD}
      # 애플리케이션에서 사용할 사용자 및 비밀번호. gvenzl/oracle-xe 이미지가 자동으로 생성해줍니다.
      APP_USER: ${ORACLE_USER}
      APP_USER_PASSWORD: ${ORACLE_PASSWORD}
    volumes:
      # Oracle 데이터 영구 저장을 위한 볼륨 설정
      - oracle_data:/opt/oracle/oradata

# 데이터 영구 저장을 위한 명명된 볼륨 정의
volumes:
  mysql_data:
  postgres_data:
  oracle_data: